-------------------------------------------------------------------------------
Test set: examples.ExamplesTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 16.47 s <<< FAILURE! - in examples.ExamplesTest
testAll[1][2]  Time elapsed: 1.093 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: employee.feature:17 - status code was: 400, expected: 200, response time: 1078, url: http://dummy.restapiexample.com/api/v1/employee/3, response: {"message":"Oops! someting issue found to fetch record.","status":"failed"}

testAll[1][3]  Time elapsed: 1.126 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: employee.feature:17 - status code was: 400, expected: 200, response time: 1033, url: http://dummy.restapiexample.com/api/v1/employee/4, response: {"message":"Oops! someting issue found to fetch record.","status":"failed"}

testAll[1][4]  Time elapsed: 2.094 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: employee.feature:34 - status code was: 401, expected: 200, response time: 921, url: http://dummy.restapiexample.com/api/v1/employee/35, response: {"data":"Record does not found.","status":"failed"}

testAll[1][5]  Time elapsed: 2.094 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: employee.feature:46 - status code was: 401, expected: 200, response time: 969, url: http://dummy.restapiexample.com/api/v1/employee/98, response: {"data":"Record does not found.","status":"failed"}

